[package]
name = "sfo-event"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.103", default-features = false, features = ["full"]}

[dev-dependencies]
async-trait = "0.1.88"

