[package]
name = "sfo-event"
version = "0.1.2"
edition = "2024"
repository = "https://github.com/wugren/sfo-event.git"
license-file = "LICENSE"
description = "event emitter"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", default-features = false, features = ["full"]}

[dev-dependencies]
async-trait = "0.1.88"

